Algoritmo "semnome"

Var

a,b,c,x1,x2,delta:real

Inicio
Escreval("Digite A:")
leia(a)
Escreval("Digite B:")
leia(b)
Escreval("Digite C:")
leia(c)
delta<-(b^2)-(4*a*c)
Enquanto delta<0 faca
Escreval("Não existem raízes reias, digite novamente os valores:")
Escreval("Digite A:")
leia(A)
Escreval("Digite B:")
leia(b)
Escreval("Digite C:")
leia(c)
delta<-(b^2)-(4*a*c)
limpatela
Fimenquanto
x1<- (-b+(raizq(delta))/2)
x2<- (-b-(raizq(delta))/2)
Escreval("X1: ", X1)
Escreval("X2: ", X2)

Fimalgoritmo