Algoritmo "semnome"

Var
valor,numero,valor_inicial,valor_final:inteiro


Inicio
Escreval("Digite o número da tabuada que deseja:")
leia(numero)
limpatela
Escreval("---------------------------------")
Escreval("Defina a abrangência da tabela ")
Escreval("---------------------------------")
Escreval("De:")
leia(valor_inicial)
Escreval("Até")
leia(valor_final)
para valor de valor_inicial ate valor_final faca
Escreval(numero," X ", valor," = ",numero*valor)
fimpara
Fimalgoritmo